デフォルトのフォントとして Inter を追加
ry0y4n/ExifFrame pull request #7
Opened 2023-07-09 16:10 UTC by 1heisuzuki

読みやすくて美しいフォント Inter を導入しました。
フォントが環境によって変わってしまうのも防ぐことができます。
https://fonts.google.com/specimen/Inter

2023-07-09 16:16 UTC, 1heisuzuki commented
コンフリクト修正中です！

2023-07-09 16:17 UTC, 1heisuzuki commented
修正 :done:

2023-07-09 17:22 UTC, 1heisuzuki commented
そもそも Webフォントが正しく読み込まれてなかったので修正中

2023-07-09 18:46 UTC, 1heisuzuki commented
対応 :done:

2023-07-10 05:42 UTC, ry0y4n commented on script.js
> +        let text1 = 'Shot on  ';
この空白追加は意図したものですか？それともタイポですか？

2023-07-10 05:44 UTC, 1heisuzuki commented on script.js
> +        let text1 = 'Shot on  ';
意図的です！Interを読み込むとなぜか空白がズレてしまったので… @ry0y4n

2023-07-10 06:22 UTC, ry0y4n requested changes

2023-07-10 06:22 UTC, ry0y4n commented on script.js
> +        // フォント読み込みとテキストの描画（フォントの二重読み込み防止処理）
Interをロードする前にはすでにsans-serifでテキスト座標を計算していることが原因のようです（ctx.measureText().widthが変わる）

```suggestion
       let text1Width = ctx.measureText(text1).width;
```

2023-07-10 06:24 UTC, ry0y4n commented on script.js
> +        // フォント読み込みとテキストの描画（フォントの二重読み込み防止処理）
draw関数に対してフォントのロードを行うといいと思います！

```
// フォント読み込みとテキストの描画（フォントの二重読み込み防止処理）
if (isFontsLoaded) {
  draw(exifData);
} else {
  loadFonts().then(function() {
      draw(exifData);
  });
}
```

2023-07-10 06:25 UTC, 1heisuzuki commented on script.js
> +        // フォント読み込みとテキストの描画（フォントの二重読み込み防止処理）
最高！承知です！

2023-07-10 06:47 UTC, 1heisuzuki commented
諸々修正しました！
Exifの枠が先に出ちゃわないように，その処理を draw()の中に入れました。

2023-07-10 07:00 UTC, ry0y4n commented on script.js
> +        // フォント読み込みとテキストの描画（フォントの二重読み込み防止処理）
:igyo:

2023-07-10 07:01 UTC, ry0y4n approved these changes

2023-07-10 07:01 UTC, merged